services:
  php:
    build:
      target: dev
    volumes:
      - "./composer.json:/app/composer.json:z"
      - "./composer.lock:/app/composer.lock:z"
      - "./symfony.lock:/app/symfony.lock:z"
      - "./.env:/app/.env:ro,z"
      - "./.env.test:/app/.env.test:ro,z"
      - "./phpunit.dist.xml:/app/phpunit.dist.xml:ro,z"
      - "./psalm.xml:/app/psalm.xml:ro,z"
      # BESCHREIBBAR: Wichtig für den PHPUnit-Cache
      - "./.phpunit.cache:/app/.phpunit.cache:Z"
      - "./src:/app/src:z"
      - "./config:/app/config:z"
      # BESCHREIBBAR: Wichtig, damit JWT-Keypairs generiert werden können
      - "./config/jwt:/app/config/jwt:z"
      - "./templates:/app/templates:z"
      - "./public:/app/public:Z"
      - "./migrations:/app/migrations:z"
      - "./bin:/app/bin:z"
      # BESCHREIBBAR: Hier lag der Hauptfehler beim Seeding
      - "./vendor:/app/vendor:z"
    develop:
      watch:
        - action: restart
          path: ./src
        - action: restart
          path: ./config
        - action: restart
          path: ./public
        - action: sync+restart
          path: ./Caddyfile
          target: /etc/frankenphp/Caddyfile
        - action: rebuild
          path: composer.json
        - action: rebuild
          path: composer.lock
        - action: rebuild
          path: Dockerfile.frankenphp

  messenger-worker:
    build:
      target: dev
    volumes:
      - "./composer.json:/app/composer.json:ro,z"
      - "./composer.lock:/app/composer.lock:ro,z"
      - "./symfony.lock:/app/symfony.lock:ro,z"
      - "./.env:/app/.env:ro,z"
      - "./src:/app/src:ro,z"
      - "./config:/app/config:ro,z"
      - "./templates:/app/templates:ro,z"
      - "./migrations:/app/migrations:ro,z"
      - "./bin:/app/bin:ro,z"
      # BESCHREIBBAR: Der Worker greift auch auf das vom Host gemountete vendor/ zu
      - "./vendor:/app/vendor:z"
    develop:
      watch:
        - action: restart
          path: ./src
        - action: restart
          path: ./config
        - action: restart
          path: ./templates
        - action: restart
          path: ./bin
        - action: rebuild
          path: composer.json
        - action: rebuild
          path: composer.lock
        - action: rebuild
          path: Dockerfile.frankenphp

###> doctrine/doctrine-bundle ###
  database:
    env_file:
      - path: .env.local
        required: false
    environment:
      POSTGRES_PASSWORD: !reset null
    ports:
      - "54321:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
