<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325093534 extends AbstractMigration
{
    public function getDescription(): string
    {
        return "";
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            "CREATE TABLE nofi_user (id UUID NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))",
        );
        $this->addSql("CREATE UNIQUE INDEX uniq_nofi_user_username ON nofi_user (username)");
        $this->addSql(
            "CREATE TABLE notification (id UUID NOT NULL, payload JSON NOT NULL, status VARCHAR(255) NOT NULL, channel VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by UUID NOT NULL, PRIMARY KEY (id))",
        );
        $this->addSql("CREATE INDEX IDX_BF5476CADE12AB56 ON notification (created_by)");
        $this->addSql(
            "CREATE TABLE notification_recipient (id UUID NOT NULL, recipient VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notification_id UUID NOT NULL, PRIMARY KEY (id))",
        );
        $this->addSql(
            "CREATE INDEX IDX_CEEDBC16EF1A9D84 ON notification_recipient (notification_id)",
        );
        $this->addSql(
            "CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))",
        );
        $this->addSql(
            "CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)",
        );
        $this->addSql(
            "ALTER TABLE notification ADD CONSTRAINT FK_BF5476CADE12AB56 FOREIGN KEY (created_by) REFERENCES nofi_user (id) ON DELETE CASCADE NOT DEFERRABLE",
        );
        $this->addSql(
            "ALTER TABLE notification_recipient ADD CONSTRAINT FK_CEEDBC16EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id) ON DELETE CASCADE NOT DEFERRABLE",
        );
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql("ALTER TABLE notification DROP CONSTRAINT FK_BF5476CADE12AB56");
        $this->addSql("ALTER TABLE notification_recipient DROP CONSTRAINT FK_CEEDBC16EF1A9D84");
        $this->addSql("DROP TABLE nofi_user");
        $this->addSql("DROP TABLE notification");
        $this->addSql("DROP TABLE notification_recipient");
        $this->addSql("DROP TABLE messenger_messages");
    }
}
